---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkout-gate-operator-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - checkout.gerardrecinto.dev
  resources:
  - checkoutgates
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - checkout.gerardrecinto.dev
  resources:
  - checkoutgates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
