//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckoutGate) DeepCopyInto(out *CheckoutGate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckoutGate.
func (in *CheckoutGate) DeepCopy() *CheckoutGate {
	if in == nil {
		return nil
	}
	out := new(CheckoutGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CheckoutGate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckoutGateList) DeepCopyInto(out *CheckoutGateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CheckoutGate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckoutGateList.
func (in *CheckoutGateList) DeepCopy() *CheckoutGateList {
	if in == nil {
		return nil
	}
	out := new(CheckoutGateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CheckoutGateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckoutGateSpec) DeepCopyInto(out *CheckoutGateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckoutGateSpec.
func (in *CheckoutGateSpec) DeepCopy() *CheckoutGateSpec {
	if in == nil {
		return nil
	}
	out := new(CheckoutGateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckoutGateStatus) DeepCopyInto(out *CheckoutGateStatus) {
	*out = *in
	in.LastEvaluated.DeepCopyInto(&out.LastEvaluated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckoutGateStatus.
func (in *CheckoutGateStatus) DeepCopy() *CheckoutGateStatus {
	if in == nil {
		return nil
	}
	out := new(CheckoutGateStatus)
	in.DeepCopyInto(out)
	return out
}
