apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manager/deployment.yaml
  - rbac/role.yaml
  - rbac/binding_and_sa.yaml
  - crd/checkout.gerardrecinto.dev_checkoutgates.yaml
  - webhook/certificate.yaml
